//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuanVanTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public int MATHUCPHAM { get; set; }
        public int MAPHIEUNHAP { get; set; }
        public int MATAIKHOAN { get; set; }
        public Nullable<decimal> SOLUONGNHAP { get; set; }
        public Nullable<double> DONGIATHUCPHAM { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual THUCPHAM THUCPHAM { get; set; }
    }
}
