//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuanVanTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONDATBAN()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public int MADATBAN { get; set; }
        public int MATAIKHOAN { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<decimal> SOLUONGNGUOI { get; set; }
        public Nullable<System.DateTime> NGAYDEN { get; set; }
        public Nullable<System.DateTime> GIODEN { get; set; }
        public Nullable<bool> TRANGTHAIDATBAN { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}
