//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuanVanTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIOHANG()
        {
            this.CHITIETGIOHANGs = new HashSet<CHITIETGIOHANG>();
            this.DUYETGIOHANGs = new HashSet<DUYETGIOHANG>();
        }
    
        public int MAGH { get; set; }
        public int MAKH { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string DIACHINHAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUYETGIOHANG> DUYETGIOHANGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
