//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuanVanTotNghiep.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLNhaHangEntities : DbContext
    {
        public QLNhaHangEntities()
            : base("name=QLNhaHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAN> BANs { get; set; }
        public virtual DbSet<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        public virtual DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DbSet<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<DONDATBAN> DONDATBANs { get; set; }
        public virtual DbSet<DONVITINH> DONVITINHs { get; set; }
        public virtual DbSet<DUYETGIOHANG> DUYETGIOHANGs { get; set; }
        public virtual DbSet<GIOHANG> GIOHANGs { get; set; }
        public virtual DbSet<HINHANH> HINHANHs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIKHACHHANG> LOAIKHACHHANGs { get; set; }
        public virtual DbSet<LOAIMONAN> LOAIMONANs { get; set; }
        public virtual DbSet<MONAN> MONANs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHAHANG> NHAHANGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<TANG> TANGs { get; set; }
        public virtual DbSet<THUCPHAM> THUCPHAMs { get; set; }
    
        public virtual ObjectResult<sp_InsUpdDelChucVu_Result> sp_InsUpdDelChucVu(Nullable<int> macv, string tencv, string motacv, string type)
        {
            var macvParameter = macv.HasValue ?
                new ObjectParameter("macv", macv) :
                new ObjectParameter("macv", typeof(int));
    
            var tencvParameter = tencv != null ?
                new ObjectParameter("tencv", tencv) :
                new ObjectParameter("tencv", typeof(string));
    
            var motacvParameter = motacv != null ?
                new ObjectParameter("motacv", motacv) :
                new ObjectParameter("motacv", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsUpdDelChucVu_Result>("sp_InsUpdDelChucVu", macvParameter, tencvParameter, motacvParameter, typeParameter);
        }
    
        public virtual ObjectResult<sp_InsUpdDelDonViTinh_Result> sp_InsUpdDelDonViTinh(Nullable<int> madvtinh, string tendvtinh, string type)
        {
            var madvtinhParameter = madvtinh.HasValue ?
                new ObjectParameter("madvtinh", madvtinh) :
                new ObjectParameter("madvtinh", typeof(int));
    
            var tendvtinhParameter = tendvtinh != null ?
                new ObjectParameter("tendvtinh", tendvtinh) :
                new ObjectParameter("tendvtinh", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsUpdDelDonViTinh_Result>("sp_InsUpdDelDonViTinh", madvtinhParameter, tendvtinhParameter, typeParameter);
        }
    
        public virtual ObjectResult<sp_InsUpdDelHinhAnh_Result> sp_InsUpdDelHinhAnh(Nullable<int> mahinhanh, string duongdan1, string duongdan2, string duongdan3, string type)
        {
            var mahinhanhParameter = mahinhanh.HasValue ?
                new ObjectParameter("mahinhanh", mahinhanh) :
                new ObjectParameter("mahinhanh", typeof(int));
    
            var duongdan1Parameter = duongdan1 != null ?
                new ObjectParameter("duongdan1", duongdan1) :
                new ObjectParameter("duongdan1", typeof(string));
    
            var duongdan2Parameter = duongdan2 != null ?
                new ObjectParameter("duongdan2", duongdan2) :
                new ObjectParameter("duongdan2", typeof(string));
    
            var duongdan3Parameter = duongdan3 != null ?
                new ObjectParameter("duongdan3", duongdan3) :
                new ObjectParameter("duongdan3", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsUpdDelHinhAnh_Result>("sp_InsUpdDelHinhAnh", mahinhanhParameter, duongdan1Parameter, duongdan2Parameter, duongdan3Parameter, typeParameter);
        }
    
        public virtual ObjectResult<sp_InsUpdDelLoaiMonAn_Result> sp_InsUpdDelLoaiMonAn(Nullable<int> maloai, string tenloai, string type)
        {
            var maloaiParameter = maloai.HasValue ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(int));
    
            var tenloaiParameter = tenloai != null ?
                new ObjectParameter("tenloai", tenloai) :
                new ObjectParameter("tenloai", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsUpdDelLoaiMonAn_Result>("sp_InsUpdDelLoaiMonAn", maloaiParameter, tenloaiParameter, typeParameter);
        }
    
        public virtual ObjectResult<sp_InsUpdDelNhaHang_Result> sp_InsUpdDelNhaHang(Nullable<int> manhahang, string tennhahang, string sdt, string gioithieu, string type)
        {
            var manhahangParameter = manhahang.HasValue ?
                new ObjectParameter("manhahang", manhahang) :
                new ObjectParameter("manhahang", typeof(int));
    
            var tennhahangParameter = tennhahang != null ?
                new ObjectParameter("tennhahang", tennhahang) :
                new ObjectParameter("tennhahang", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var gioithieuParameter = gioithieu != null ?
                new ObjectParameter("gioithieu", gioithieu) :
                new ObjectParameter("gioithieu", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsUpdDelNhaHang_Result>("sp_InsUpdDelNhaHang", manhahangParameter, tennhahangParameter, sdtParameter, gioithieuParameter, typeParameter);
        }
    
        public virtual int usp_insert_order(ObjectParameter order_id, Nullable<System.DateTime> order_date, Nullable<int> custom_id, Nullable<bool> status, string received_address)
        {
            var order_dateParameter = order_date.HasValue ?
                new ObjectParameter("order_date", order_date) :
                new ObjectParameter("order_date", typeof(System.DateTime));
    
            var custom_idParameter = custom_id.HasValue ?
                new ObjectParameter("custom_id", custom_id) :
                new ObjectParameter("custom_id", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            var received_addressParameter = received_address != null ?
                new ObjectParameter("received_address", received_address) :
                new ObjectParameter("received_address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_order", order_id, order_dateParameter, custom_idParameter, statusParameter, received_addressParameter);
        }
    
        public virtual ObjectResult<sp_InsUpdDelTang_Result> sp_InsUpdDelTang(Nullable<int> matang, Nullable<int> manhahang, string tentang, string type)
        {
            var matangParameter = matang.HasValue ?
                new ObjectParameter("matang", matang) :
                new ObjectParameter("matang", typeof(int));
    
            var manhahangParameter = manhahang.HasValue ?
                new ObjectParameter("manhahang", manhahang) :
                new ObjectParameter("manhahang", typeof(int));
    
            var tentangParameter = tentang != null ?
                new ObjectParameter("tentang", tentang) :
                new ObjectParameter("tentang", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsUpdDelTang_Result>("sp_InsUpdDelTang", matangParameter, manhahangParameter, tentangParameter, typeParameter);
        }
    
        public virtual ObjectResult<sp_InsUpdDelBan_Result> sp_InsUpdDelBan(Nullable<int> maban, Nullable<int> matang, string tentang, Nullable<bool> trangthaiban, string type)
        {
            var mabanParameter = maban.HasValue ?
                new ObjectParameter("maban", maban) :
                new ObjectParameter("maban", typeof(int));
    
            var matangParameter = matang.HasValue ?
                new ObjectParameter("matang", matang) :
                new ObjectParameter("matang", typeof(int));
    
            var tentangParameter = tentang != null ?
                new ObjectParameter("tentang", tentang) :
                new ObjectParameter("tentang", typeof(string));
    
            var trangthaibanParameter = trangthaiban.HasValue ?
                new ObjectParameter("trangthaiban", trangthaiban) :
                new ObjectParameter("trangthaiban", typeof(bool));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsUpdDelBan_Result>("sp_InsUpdDelBan", mabanParameter, matangParameter, tentangParameter, trangthaibanParameter, typeParameter);
        }
    
        public virtual ObjectResult<sp_InsUpdDelMonAn_Result> sp_InsUpdDelMonAn(Nullable<int> mamon, Nullable<int> madvtinh, Nullable<int> maloai, Nullable<int> mahinhanh, string tengoi, Nullable<double> dongia, string mota, string cachlam, Nullable<System.DateTime> ngaytao, string type)
        {
            var mamonParameter = mamon.HasValue ?
                new ObjectParameter("mamon", mamon) :
                new ObjectParameter("mamon", typeof(int));
    
            var madvtinhParameter = madvtinh.HasValue ?
                new ObjectParameter("madvtinh", madvtinh) :
                new ObjectParameter("madvtinh", typeof(int));
    
            var maloaiParameter = maloai.HasValue ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(int));
    
            var mahinhanhParameter = mahinhanh.HasValue ?
                new ObjectParameter("mahinhanh", mahinhanh) :
                new ObjectParameter("mahinhanh", typeof(int));
    
            var tengoiParameter = tengoi != null ?
                new ObjectParameter("tengoi", tengoi) :
                new ObjectParameter("tengoi", typeof(string));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(double));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var cachlamParameter = cachlam != null ?
                new ObjectParameter("cachlam", cachlam) :
                new ObjectParameter("cachlam", typeof(string));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("ngaytao", ngaytao) :
                new ObjectParameter("ngaytao", typeof(System.DateTime));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsUpdDelMonAn_Result>("sp_InsUpdDelMonAn", mamonParameter, madvtinhParameter, maloaiParameter, mahinhanhParameter, tengoiParameter, dongiaParameter, motaParameter, cachlamParameter, ngaytaoParameter, typeParameter);
        }
    
        public virtual ObjectResult<sp_InsUpdDelNhanVien_Result> sp_InsUpdDelNhanVien(Nullable<int> manv, Nullable<int> manhahang, Nullable<int> macv, string hoten_nv, string sdt_nv, string diachi_nv, string email_nv, Nullable<System.DateTime> ngaysinh_nv, Nullable<bool> gioitinh_nv, string type)
        {
            var manvParameter = manv.HasValue ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(int));
    
            var manhahangParameter = manhahang.HasValue ?
                new ObjectParameter("manhahang", manhahang) :
                new ObjectParameter("manhahang", typeof(int));
    
            var macvParameter = macv.HasValue ?
                new ObjectParameter("macv", macv) :
                new ObjectParameter("macv", typeof(int));
    
            var hoten_nvParameter = hoten_nv != null ?
                new ObjectParameter("hoten_nv", hoten_nv) :
                new ObjectParameter("hoten_nv", typeof(string));
    
            var sdt_nvParameter = sdt_nv != null ?
                new ObjectParameter("sdt_nv", sdt_nv) :
                new ObjectParameter("sdt_nv", typeof(string));
    
            var diachi_nvParameter = diachi_nv != null ?
                new ObjectParameter("diachi_nv", diachi_nv) :
                new ObjectParameter("diachi_nv", typeof(string));
    
            var email_nvParameter = email_nv != null ?
                new ObjectParameter("email_nv", email_nv) :
                new ObjectParameter("email_nv", typeof(string));
    
            var ngaysinh_nvParameter = ngaysinh_nv.HasValue ?
                new ObjectParameter("ngaysinh_nv", ngaysinh_nv) :
                new ObjectParameter("ngaysinh_nv", typeof(System.DateTime));
    
            var gioitinh_nvParameter = gioitinh_nv.HasValue ?
                new ObjectParameter("gioitinh_nv", gioitinh_nv) :
                new ObjectParameter("gioitinh_nv", typeof(bool));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsUpdDelNhanVien_Result>("sp_InsUpdDelNhanVien", manvParameter, manhahangParameter, macvParameter, hoten_nvParameter, sdt_nvParameter, diachi_nvParameter, email_nvParameter, ngaysinh_nvParameter, gioitinh_nvParameter, typeParameter);
        }
    
        public virtual ObjectResult<sp_InsUpdDelTaiKhoan_Result> sp_InsUpdDelTaiKhoan(Nullable<int> mataikhoan, Nullable<int> manv, string tendangnhap, string matkhau, string quyensd, Nullable<bool> trangthaikichhoat, string type)
        {
            var mataikhoanParameter = mataikhoan.HasValue ?
                new ObjectParameter("mataikhoan", mataikhoan) :
                new ObjectParameter("mataikhoan", typeof(int));
    
            var manvParameter = manv.HasValue ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(int));
    
            var tendangnhapParameter = tendangnhap != null ?
                new ObjectParameter("tendangnhap", tendangnhap) :
                new ObjectParameter("tendangnhap", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var quyensdParameter = quyensd != null ?
                new ObjectParameter("quyensd", quyensd) :
                new ObjectParameter("quyensd", typeof(string));
    
            var trangthaikichhoatParameter = trangthaikichhoat.HasValue ?
                new ObjectParameter("trangthaikichhoat", trangthaikichhoat) :
                new ObjectParameter("trangthaikichhoat", typeof(bool));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsUpdDelTaiKhoan_Result>("sp_InsUpdDelTaiKhoan", mataikhoanParameter, manvParameter, tendangnhapParameter, matkhauParameter, quyensdParameter, trangthaikichhoatParameter, typeParameter);
        }
    
        public virtual ObjectResult<sp_InsUpdDelThucPham_Result> sp_InsUpdDelThucPham(Nullable<int> manthucpham, string tenthucpham, string dvtinh, string type)
        {
            var manthucphamParameter = manthucpham.HasValue ?
                new ObjectParameter("manthucpham", manthucpham) :
                new ObjectParameter("manthucpham", typeof(int));
    
            var tenthucphamParameter = tenthucpham != null ?
                new ObjectParameter("tenthucpham", tenthucpham) :
                new ObjectParameter("tenthucpham", typeof(string));
    
            var dvtinhParameter = dvtinh != null ?
                new ObjectParameter("dvtinh", dvtinh) :
                new ObjectParameter("dvtinh", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsUpdDelThucPham_Result>("sp_InsUpdDelThucPham", manthucphamParameter, tenthucphamParameter, dvtinhParameter, typeParameter);
        }
    }
}
