//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuanVanTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public int MANV { get; set; }
        public int MANHAHANG { get; set; }
        public int MACV { get; set; }
        public string HOTEN_NV { get; set; }
        public string SDT_NV { get; set; }
        public string DIACHI_NV { get; set; }
        public string EMAIL_NV { get; set; }
        public Nullable<System.DateTime> NGAYSINH_NV { get; set; }
        public Nullable<bool> GIOITINH_NV { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual NHAHANG NHAHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
